name: monkey-gaze-tracker
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytables
  - hdf5
  - lzo
  - lzo2
  - pip
  - pip:
      - deeplabcut
      - opencv-python
      - pyyaml
      - numpy
      - pandas
      - matplotlib
