name: monkey-gaze-tracker
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - deeplabcut
      - opencv-python
      - pyyaml
      - numpy
      - pandas
      - matplotlib

