name: monkey-gaze-tracker
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytables       # Precompiled PyTables from conda-forge
  - hdf5
  - lzo
  - opencv
  - numpy
  - pandas
  - matplotlib
  - pip
  - pip:
      - deeplabcut
      - opencv-python
      - pyyaml
      - numpy
      - pandas
      - matplotlib
      - dlclibrary>=0.0.6
      - filterpy>=1.4.4
      - ruamel.yaml>=0.15.0
      - imgaug>=0.4.0
      - imageio-ffmpeg
      - numba>=0.54
      - networkx>=2.6
      - scikit-image>=0.17
      - scikit-learn>=1.0
      - scipy>=1.9
      - statsmodels>=0.11
      - torch
      - tqdm
      - Pillow>=7.1
